PINECONE_API_KEY = "pcsk_3562qp_NjYv6nGhcw3GXj5r5f9jJAULgyJMCh9EXis1pwfbPgfgiaHzUDQgUUAir7Gu53K"
GOOGLE_API_KEY = "AIzaSyDsEliNWB63FWMU9WKci0gJJrtfiU3iMYw"
PINECONE_CLOUD = "aws"
PINECONE_REGION = "us-east-1"
HF_TOKEN = "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"
DATABASE_URL = "postgresql://postgres.asgmwkjqetoxuywixgot:Naaorumuttapaya%40123@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
GEMINI_MODEL = "gemini-2.0-flash"
